### ISSUE TITLE
Device code flow polling request failed

### ISSUE THREAD

**Issue by ashleylst** [indigo-dc/oidc-agent#454]
I was trying to use ```oidc-gen``` to generate account info, I have a public client registered and it's saved in ```pubclients.config```. So I did:
```oidc-gen --pub --issuer https://central-proxy.fenix-ri.eu --configuration-endpoint https://central-webapp.fenix-ri.eu/oidc/.well-known/openid-configuration --flow device fenix```

I received the details to go to the website and enter the code. And then I received an error ```Error: invalid_request: client_id: field required```, which appeared to be an error from Device Access Token Request (in polling process) as defined in [https://www.rfc-editor.org/rfc/rfc8628.html#section-3.4](url).

I quickly looked at the code where the info is generated for device code flow, I noticed that client_id was indeed commented out in the function: https://github.com/indigo-dc/oidc-agent/blob/69f2b1cb1b481937cc58573d0306482dc87ddc80/src/oidc-agent/oidc/flows/device.c#L18 
By the standards of the RFC of Device Authorization Grant, the Device Access Token Request may include client_id. And my understanding is that if a public client is used in this case, it's required to include client_id. Hence I think this should be addressed in the tool, at least one should have the option to add client_id in the request, right?

**Comment by zachmann** [comment]
@ashleylst thanks for reporting this issue.
Indeed, it seems that we were not doing things here 100% correctly.
I pushed a fix to the [`fix/device_client_id`](https://github.com/indigo-dc/oidc-agent/tree/fix/device_client_id) branch. Could you please try it out and assure that it works as expected with your OP. You can either build the binary from the source or download the package for your distro from https://repo.data.kit.edu/devel/

**Comment by zachmann** [comment]
@ashleylst could you please verify the fix

**Comment by ashleylst** [comment]
> 

Sorry I wasn't available last week. I just tried, I did `cd /etc/yum.repos.d; wget https://repo.data.kit.edu/devel/data-kit-edu-centos7.repo; yum install oidc-agent`. It seems I got version 4.3.2 and the problem is still there. Do I need to build the package myself?

**Comment by zachmann** [comment]
You should be able to install from the repo.
I just updated the signatures, maybe there was a problem there. Please try again. The certainly is a version `4.4.0` as well as `4.4.1` in the repo.
If it is not installed automatically, you can download it install it manually.
https://repo.data.kit.edu/devel/centos/7/

**Comment by ashleylst** [comment]
I didn't find a x86_64.rpm so I did
`rpm -vv -Uvh oidc-agent-4.4.1-1.el7.src.rpm`
`rpmbuild -ba ./rpmbuild/SPECS/oidc-agent.spec`
Then I install the packages it gives. Then it works perfectly for me, I can get an oidc token now, thanks!
