### ISSUE TITLE
Oidcd dies when using Mytoken server

### ISSUE THREAD

**Issue by Nithe14** [indigo-dc/oidc-agent#526]
The commands `oidc-add` and `oidc-token` are returning an error message stating: 
```bash
2023-07-18 11:45:13 oidc-agent.p ERROR: oidcd died
``` 
This error occurs regardless of whether an account is loaded or not. I am able to create a new profile, but I cannot obtain a token using the `oidc-token` command. This issue only happens when I use profile with Mytoken server as a provider. An example of the profile generation command is as follows:
```bash
$ oidc-gen -m --prompt=cli --flow=device --mytoken-url=$MYTOKEN_ADDR --issuer=$ISSUER --redirect-uri=$REDIRECT_URI --scope=openid --scope=profile --scope=offline_access
```
I have attempted to troubleshoot the issue by using the "--debug" option and running "oidc-agent" as a non-daemon (-d), as well as enabling various debug options such as "--debug," "--status," and "--log-stderr." However, no additional log messages are generated.
I have tested the Mytoken server using the web client, and it works well. Therefore, I assume this problem is specific to oidc-agent.
Maybe related to #261.

Oidc-agent Version: 4.5.2
Operating Systems tested: CentOS 7, Debian 11 (Bullseye), Arch linux 
Mytoken server version tested: 0.8.2-pr11

**Comment by zachmann** [comment]
thanks for the information.

The issue is already fixed in the `prerel` branch. It will be released as oidc-agent 5. Packages are available in our prerel repo (well, not for arch).

I also cherry-picked the commit that fixes this issue and pushed it to it's own branch:
https://github.com/indigo-dc/oidc-agent/tree/fix/mytoken-AT-segfault

However, unfortunately I currently cannot make a packed release.
But if you build it yourself you can work from either the fix-branch or prerel.

**Comment by zachmann** [comment]
> Thank you for the response! Unfortunately, the `prerel` branch did not resolve this issue. I am currently able to use oidc-token with the previously generated mytoken account, but I can't generate a new account configuration using the --mytoken-url option. When running `oidc-gen` command (mentioned above), I receive the following error message:
> 
> ```shell
> Error: invalid_request: unknown include name: 'agent'
> ```

This error comes from your mytoken server. The agent tries to create a mytoken with the `agent` profile, but that does not exist on your mytoken server.
You can create it on the mytoken server - but there currently is no documentation how this is done. 
You can also use the `--mytoken-profile=""` option to use an empty profile. Note that then you might need to adjust the capabilities in the mytoken consent screen.

> I also tried to build the `fix/mytoken-AT-segfault` branch. In this case, `oidc-gen` works fine, but I encountered errors using the `oidc-token` command:
> 
> ```shell
> oidc-token: error while loading shared libraries: liboidc-agent.so.4: cannot open shared object file: No such file or directory
> ```
oidc-token uses the liboidc-agent. The error says that it cannot find it, so it's something about that, usually the shared object file is installed into a location where the system finds it.
It's a bit strange that you get the error for the fix brnach but not prerel.

You can check if the lib is installed (`make install` should do that), or include the location of the build lib into `LD_PRELOAD`, e.g. 
```shell
export LD_PRELOAD=${OIDC_AGENT_GIT}/lib/api/liboidc-agent.so.4.5.2
```

**Comment by Nithe14** [comment]
This works like a charm now!
Either using the prerel branch with `--mytoken-profile=""` and exporting `LD_PRELOAD` using fix branch. I continue to use prerel because of the package repo, but I'm eagerly waiting for the fix release!
Thank you!

**Comment by Nithe14** [comment]
This issue has reappeared in oidc-agent 5.3.2. I’m getting:
```
Error: oidcd died
```
whenever I request or load a token using `oidc-token` or `oidc-add`. This occurs only when requesting mytoken profile as described previously:

> This error occurs regardless of whether an account is loaded or not. I am able to create a new profile, but I cannot obtain a token using the oidc-token command. This issue only happens when I use profile with Mytoken server as a provider. [...]

Profile generation command I've used:
```
$ oidc-gen -m --prompt=cli --pw-prompt=cli --flow=device --mytoken-url=$MYTOKEN_ADDR --mytoken-profile="" --issuer=$ISSUER --redirect-uri=$REDIRECT_URI --scope=openid --scope=profile --scope=email --scope=offline_access $PROFILE_NAME;
```

I have also tested with the prerel version of MyToken (0.11.0-pr114), but the problem still occurs.

@zachmann Could you please reopen this issue?
